mockedVersion: 0.1.1
webServer:
  interface: 0.0.0.0
  port: 8080
  appPath: /
  staticPath: /static
paths:
  longTemplate: templates/long.html
  shortTemplate: templates/short.gtpl
versions:
- version: 0.1.0
  vars:
    emoji: "ğŸ§˜â€â™‚ï¸â¬œğŸ¦ "
    message: "[Initial commit] Add a meal serving cloth (Sofreh)"
- version: 0.1.1
  vars:
    emoji: "ğŸ§˜â€â™‚ï¸â¬œâœ¨"
    message: "[Fix] Cleanup the cloth"
- version: 0.2.0
  vars:
    emoji: "ğŸ§˜â€â™‚ï¸ğŸğŸ¦ "
    message: "[Feature] Add Sangak bread"
- version: 0.2.1
  vars:
    emoji: "ğŸ§˜â€â™‚ï¸ğŸâœ¨"
    message: "[Fix] Use perfectly baked Sangak bread"
- version: 0.3.0
  vars:
    emoji: "ğŸ§˜â€â™‚ï¸ğŸ¥–ğŸ¦ "
    message: "[Feature] Add Barbari bread"
- version: 0.3.1
  vars:
    emoji: "ğŸ§˜â€â™‚ï¸ğŸ¥–âœ¨"
    message: "[Fix] Use unbiten Barbari bread"
- version: 1.0.0
  vars:
    emoji: "ğŸ§ğŸªµğŸ¦ "
    message: "[Major] Add a table for breakfast"
- version: 1.0.1
  vars:
    emoji: "ğŸ§ğŸªµâœ¨"
    message: "[Fix] Fix the table legs"
- version: 1.1.0
  vars:
    emoji: "ğŸ§ğŸ§€ğŸ¦ "
    message: "[Feature] Add a few pieces of cheese"
- version: 1.1.1
  vars:
    emoji: "ğŸ§ğŸ§€âœ¨"
    message: "[Fix] Serve the cheese properly"
- version: 1.2.0
  vars:
    emoji: "ğŸ§ğŸ«–ğŸ¦ "
    message: "[Feature] Add a Shirin Chay"
- version: 1.2.1
  vars:
    emoji: "ğŸ§ğŸ«–âœ¨"
    message: "[Fix] Serve the tea properly"
- version: 2.0.0
  vars:
    emoji: "ğŸª‘ğŸª‘ğŸ¦ "
    message: "[Major] Add chairs to the breakfast table"
- version: 2.0.1
  vars:
    emoji: "ğŸª‘ğŸª‘âœ¨"
    message: "[Fix] Fix the broken chairs"
- version: 2.1.0
  vars:
    emoji: "ğŸª‘ğŸ¥œğŸ¦ "
    message: "[Feature] Add a few walnuts"
- version: 2.1.1
  vars:
    emoji: "ğŸª‘ğŸ¥œâœ¨"
    message: "[Fix] Serve the walnuts without shell"
- version: 2.2.0
  vars:
    emoji: "ğŸª‘ğŸ²ğŸ¦ "
    message: "[Feature] Add a bowl of Halim"
- version: 2.2.2
  vars:
    emoji: "ğŸª‘ğŸ²âœ¨"
    message: "[Fix] Serve the Halim better"
versionModifiers:
- format: 0.*.*
  vars:
    bgColor1: "#4b6cb7"
    bgColor2: "#182848"
    textColor: "#323641"
- format: 1.*.*
  vars:
    bgColor1: "#FE28A2"
    bgColor2: "#570b36"
    textColor: "#3d3037"
- format: 2.*.*
  vars:
    bgColor1: "#00A693"
    bgColor2: "#003b34"
    textColor: "#2f4745"
